services:
  litkeeper:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "5000:5000"
      
    volumes:
      - ./data:/litkeeper/app/data
      - ./stories:/litkeeper/app/stories
      
    environment:
      - ENABLE_LIBRARY=true
