services:
  litkeeper:
    image: ghcr.io/redwoodstory/litkeeper:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Set /stories mount for all story-related files (epubs, html, covers)
      - ./stories:/litkeeper/app/data/stories

      # Set /data mount to persist database, secret key, and other app data
      - ./data:/litkeeper/app/data
      
    environment:
      # Set to false to hide library UI (download-only mode)
      - ENABLE_LIBRARY=true

      # Configure notification services based on Apprise: https://github.com/caronc/apprise#supported-notifications
      - NOTIFICATION_URLS=

      # Copy EPUBs to an external directory for integration with other apps (e.g., Calibre-Web)
      # Example: /path/to/calibre-web/auto-import
      - EXTERNAL_EPUB_PATH=

      # Set a cron schedule to check for new chapters of stories you have downloaded
      - AUTO_UPDATE_SCHEDULE=