"""add literotica community stats to stories

Revision ID: 91eb3b2b1034
Revises: a1b2c3d4e5f6
Create Date: 2026-06-19 12:26:17.683619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eb3b2b1034'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('stories')}

    with op.batch_alter_table('stories', schema=None) as batch_op:
        if 'literotica_score' not in existing_columns:
            batch_op.add_column(sa.Column('literotica_score', sa.Float(), nullable=True))
        if 'literotica_views' not in existing_columns:
            batch_op.add_column(sa.Column('literotica_views', sa.Integer(), nullable=True))
        if 'literotica_favorites' not in existing_columns:
            batch_op.add_column(sa.Column('literotica_favorites', sa.Integer(), nullable=True))
        if 'literotica_comments' not in existing_columns:
            batch_op.add_column(sa.Column('literotica_comments', sa.Integer(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('literotica_comments')
        batch_op.drop_column('literotica_favorites')
        batch_op.drop_column('literotica_views')
        batch_op.drop_column('literotica_score')

    # ### end Alembic commands ###
