"""Remove bookmarks and highlights tables and add auto_update fields to Story

Revision ID: 978f4639ab8d
Revises: 
Create Date: 2026-01-05 09:14:31.659784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978f4639ab8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'bookmarks' in inspector.get_table_names():
        with op.batch_alter_table('bookmarks', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_bookmarks_story_id'))
        op.drop_table('bookmarks')

    if 'highlights' in inspector.get_table_names():
        with op.batch_alter_table('highlights', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_highlights_story_id'))
        op.drop_table('highlights')
    
    # Check which columns already exist in stories table
    existing_columns = {col['name'] for col in inspector.get_columns('stories')}
    
    with op.batch_alter_table('stories', schema=None) as batch_op:
        if 'auto_update_enabled' not in existing_columns:
            batch_op.add_column(sa.Column('auto_update_enabled', sa.Boolean(), nullable=False, server_default='1'))
        if 'last_update_check_at' not in existing_columns:
            batch_op.add_column(sa.Column('last_update_check_at', sa.DateTime(), nullable=True))
        if 'content_hash' not in existing_columns:
            batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('content_hash')
        batch_op.drop_column('last_update_check_at')
        batch_op.drop_column('auto_update_enabled')

    op.create_table('highlights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), nullable=False),
    sa.Column('paragraph_number', sa.INTEGER(), nullable=False),
    sa.Column('start_offset', sa.INTEGER(), nullable=True),
    sa.Column('end_offset', sa.INTEGER(), nullable=True),
    sa.Column('highlighted_text', sa.TEXT(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlights_story_id'), ['story_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), nullable=False),
    sa.Column('paragraph_number', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###
