"""add series url to stories

Revision ID: e5471813f87f
Revises: 978f4639ab8d
Create Date: 2026-01-05 13:34:05.393436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5471813f87f'
down_revision = '978f4639ab8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('stories')}
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('stories')}
    
    with op.batch_alter_table('stories', schema=None) as batch_op:
        if 'literotica_series_url' not in existing_columns:
            batch_op.add_column(sa.Column('literotica_series_url', sa.String(length=512), nullable=True))
        if 'ix_stories_literotica_series_url' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_stories_literotica_series_url'), ['literotica_series_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_literotica_series_url'))
        batch_op.drop_column('literotica_series_url')

    # ### end Alembic commands ###
