"""drop curated_stories table

Revision ID: f18425943940
Revises: 61fb23c819e4
Create Date: 2026-06-15 16:10:02.276547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18425943940'
down_revision = '61fb23c819e4'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS curated_stories"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_stories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('favorites', sa.INTEGER(), nullable=True),
    sa.Column('author_name', sa.VARCHAR(), nullable=True),
    sa.Column('author_url', sa.VARCHAR(), nullable=True),
    sa.Column('date_approve', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('is_series', sa.BOOLEAN(), nullable=True),
    sa.Column('imported_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curated_stories', schema=None) as batch_op:
        batch_op.create_index('ix_curated_stories_url', ['url'], unique=1)
        batch_op.create_index('ix_curated_stories_category', ['category'], unique=False)

    # ### end Alembic commands ###
